// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhjucbkqyamutshfspyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoanVjYmtxeWFtdXRzaGZzcHlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3Mzc5OTgsImV4cCI6MjA2NTMxMzk5OH0.ZQmD-ELWa0-M_8qNv5drxm0C7tTp44wzRKWl5RPjzx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);